version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "/tmp:/tmp"
  db:
    image: mdillon/postgis:9.6
    volumes:
      - "db-data:/var/lib/postgresql/data "
  web:
    build: .
    environment:
      DB_PORT: 5432
    volumes:
      - "/tmp:/tmp"
    depends_on:
      - db
volumes:
  db-data: