version: "3"
services:
  nginx:
  db:
    environment:
      POSTGRES_USER: "tag_user"
      POSTGRES_PASSWORD: "somepass"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
  web:
    environment:
      DEBUG: 1
      DB_HOST: "db"
    env_file:
      - local.env
    volumes:
      - ".:/code"
    depends_on:
      - db
    ports:
      - "8000:8000"